# Site settings
title: Jonathan Zúñiga
email: jonathanzuniga@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Jonathan, and I use this space to collect my thoughts about mobile app & game development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jonathan_zuniga
github_username:  jonathanzuniga

# Build settings
markdown: kramdown
