# Site settings.
title: Jonathan Zúñiga
email: jonathanzuniga@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hola, mi nombre es Jonathan y en este espacio compartire algunos pensamientos así como observaciones de mi vida diaria.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jonathan_zuniga
github_username: jonathanzuniga
facebook_username: jonathanzuniga
googleplus_username: '110998212527855988388'
instagram_username: zuniga.jonathan
pinterest_username: jonathanzuniga

# Build settings.
markdown: kramdown

# Author details.
authors:
  jonathan:
    name: Jonathan Zúñiga
    email: jonathanzuniga@gmail.com
    web: http://

excerpt_separator: <!--more-->

# Custom permalink.
permalink: /:title
