# Site settings
title: Jonathan Zúñiga
email: jonathanzuniga@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hola, mi nombre es Jonathan y en este espacio compartire algunos pensamientos así como observaciones de mi vida diaria.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Author details
authors:
  jonathan:
    avatar: jonathan.jpg
    name: Jonathan
    lastname: Zúñiga
    email: jonathanzuniga@gmail.com
    web: http://
    # social media
    facebook_username: jonathanzuniga
    flickr_username: jonathan_zuniga
    github_username: jonathanzuniga
    googleplus_username: '110998212527855988388'
    instagram_username: zuniga.jonathan
    linkedin_username: jonathan-zúñiga-09b403ab
    medium_username: jonathanzuniga
    pinterest_username: jonathanzuniga
    spotify_username: jonathanzuniga
    shelf_username: jonathan
    twitter_username: jonathan_zuniga

excerpt_separator: <!--more-->

# Custom permalink
permalink: /:year/:month/:day/:title

timezone: America/Tijuana

# gems: ['jekyll-twitter-plugin']
# gems: ['jekyll-timeago']

# jekyll_timeago:
#   depth: 2 # Level of detail
#   today: 'el día de hoy'
#   yesterday: 'el día de ayer'
#   tomorrow: 'mañana'
#   and: 'y'
#   # suffix: 'ago'
#   suffix: ''
#   prefix: 'hace'
#   suffix_future: ''
#   prefix_future: 'en'
#   years: 'años'
#   year: 'año'
#   months: 'meses'
#   month: 'mes'
#   weeks: 'semanas'
#   week: 'semana'
#   days: 'días'
#   day: 'día'

# gems: ['emoji_for_jekyll']

# tag_page_layout: tag_page
# tag_page_dir: etiqueta
# tag_permalink_style: pretty
